// Package ecu reads and writes ME7Logger .ecu files.
package ecu

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"me7-logger/ident"
	"me7-logger/record"
)

// File is one .ecu characteristics file.
type File struct {
	Version   string
	Connect   string
	Fast      byte
	LogSpeed  int
	ID        ident.ID
	Items     []record.Item
	ImageName string
	ImageSize int
	MapName   string
}

// Parse reads an .ecu file. The on-disk encoding is Latin-1.
func Parse(path string) (*File, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return ParseBytes(b)
}

// ParseBytes parses an .ecu document.
func ParseBytes(b []byte) (*File, error) {
	text := latin1(b)
	f := &File{Version: "1.20", LogSpeed: 56000, MapName: "catalog.yaml"}
	section := ""
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimRight(line, "\r")
		trim := strings.TrimSpace(line)
		if trim == "" {
			continue
		}
		if strings.HasPrefix(trim, "[") && strings.HasSuffix(trim, "]") {
			section = trim
			continue
		}
		if strings.HasPrefix(trim, ";") || strings.HasPrefix(trim, "#") {
			continue
		}
		if it, ok := parseMeas(trim); ok && (section == "[Measurements]" || section == "") {
			f.Items = append(f.Items, it)
			continue
		}
		switch section {
		case "[Version]", "[Communication]", "[Identification]", "":
			key, val, comment := splitKV(trim)
			applyKV(f, key, val, comment)
		}
	}
	return f, nil
}

func applyKV(f *File, key, val, comment string) {
	switch key {
	case "Version":
		f.Version = val
	case "Connect":
		f.Connect = val
		if b, ok := fastFrom(comment); ok {
			f.Fast = b
		}
	case "Communicate":
		if f.Fast == 0 {
			if b, ok := fastFrom(comment); ok {
				f.Fast = b
			}
		}
	case "LogSpeed":
		if n, err := strconv.Atoi(val); err == nil {
			f.LogSpeed = n
		}
	case "HWNumber":
		f.ID.HWNumber = unwrap(val)
	case "SWNumber":
		f.ID.SWNumber = unwrap(val)
	case "PartNumber":
		f.ID.PartNumber = unwrap(val)
	case "SWVersion":
		f.ID.SWVersion = unwrap(val)
	case "EngineId":
		f.ID.EngineID = unwrap(val)
	}
}

func fastFrom(comment string) (byte, bool) {
	for _, tok := range strings.FieldsFunc(comment, func(r rune) bool {
		return r == ',' || r == ';' || r == ' '
	}) {
		if strings.HasPrefix(tok, "FAST-0x") || strings.HasPrefix(tok, "HM2-0x") {
			v, err := strconv.ParseUint(tok[len(tok)-2:], 16, 8)
			if err == nil {
				return byte(v), true
			}
		}
	}
	return 0, false
}

func splitKV(line string) (key, val, comment string) {
	if i := strings.Index(line, ";"); i >= 0 {
		comment = strings.TrimSpace(line[i+1:])
		line = line[:i]
	}
	parts := strings.SplitN(line, "=", 2)
	if len(parts) != 2 {
		return "", "", comment
	}
	return strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1]), comment
}

func parseMeas(line string) (record.Item, bool) {
	f := splitComma(line)
	if len(f) < 11 {
		return record.Item{}, false
	}
	addr, err := parseHex(f[2])
	if err != nil {
		return record.Item{}, false
	}
	sz, err := strconv.Atoi(f[3])
	if err != nil {
		return record.Item{}, false
	}
	mask, err := parseHex(f[4])
	if err != nil {
		return record.Item{}, false
	}
	s, err := strconv.Atoi(f[6])
	if err != nil {
		return record.Item{}, false
	}
	inv, err := strconv.Atoi(f[7])
	if err != nil {
		return record.Item{}, false
	}
	a, err := strconv.ParseFloat(f[8], 64)
	if err != nil {
		return record.Item{}, false
	}
	b, err := strconv.ParseFloat(f[9], 64)
	if err != nil {
		return record.Item{}, false
	}
	comment := unwrap(f[10])
	guessed := strings.Contains(comment, "(guessed address)")
	return record.Item{
		Name:    f[0],
		Alias:   unwrap(f[1]),
		Addr:    uint32(addr),
		Size:    sz,
		Bitmask: uint16(mask),
		Unit:    unwrap(f[5]),
		Signed:  s != 0,
		Inverse: inv != 0,
		A:       a,
		B:       b,
		Comment: comment,
		Guessed: guessed,
	}, true
}

func parseHex(s string) (int64, error) {
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "0x")
	s = strings.TrimPrefix(s, "0X")
	return strconv.ParseInt(s, 16, 64)
}

// Bytes encodes the file as Latin-1 with LF line endings.
func (f *File) Bytes() []byte {
	var b strings.Builder
	img := f.ImageName
	if img == "" {
		img = "image.bin"
	}
	mapName := f.MapName
	if mapName == "" {
		mapName = "catalog.yaml"
	}
	ver := f.Version
	if ver == "" {
		ver = "1.20"
	}
	speed := f.LogSpeed
	if speed == 0 {
		speed = 56000
	}
	fmt.Fprintf(&b, ";\n; ECU characteristics for logging\n;\n; Generated by me7info\n;\n")
	fmt.Fprintf(&b, "; Flash image:  %s (size=%d)\n; Used mapfile: %s\n;\n", img, f.ImageSize, mapName)
	fmt.Fprintf(&b, "[Version]\nVersion           = %s\n\n", ver)
	b.WriteString("[Communication]\n")
	conn, hm := connectLines(f.Connect, f.Fast)
	b.WriteString(conn)
	b.WriteString(hm)
	fmt.Fprintf(&b, "LogSpeed     = %-10d ; Possible values: 10400, 14400, 19200, 38400, 56000, 57600, 125000\n", speed)
	b.WriteString("[Identification]\n")
	writeID(&b, "HWNumber", f.ID.HWNumber)
	writeID(&b, "SWNumber", f.ID.SWNumber)
	writeID(&b, "PartNumber", f.ID.PartNumber)
	writeID(&b, "SWVersion", f.ID.SWVersion)
	writeID(&b, "EngineId", f.ID.EngineID)
	b.WriteString("\n[Measurements]\n")
	b.WriteString("; Conversion factors:\n")
	b.WriteString(";   S -> 0 = unsigned, 1 = signed value\n")
	b.WriteString(";   I -> 0 = normal, 1 = inverse conversion\n")
	b.WriteString(";   A -> factor\n")
	b.WriteString(";   B -> offset\n")
	b.WriteString("; Normal conversion:  phys = A * internal - B\n")
	b.WriteString("; Inverse conversion: phys = A / (internal - B)\n\n")
	b.WriteString(";Name           , {Alias}                           , Address, Size, Bitmask, {Unit},    S, I,            A,      B, Comment\n")
	for _, it := range f.Items {
		b.WriteString(formatMeas(it))
		b.WriteByte('\n')
	}
	return latin1Bytes(b.String())
}

func connectLines(connect string, fast byte) (string, string) {
	fastTxt := ""
	if fast != 0 {
		fastTxt = fmt.Sprintf("0x%02X", fast)
	}
	if connect == "" {
		return "; Connect      =\n", "Communicate  = HM0\n"
	}
	conn := fmt.Sprintf("Connect      = %s", connect)
	hm := "Communicate  = HM0"
	if fastTxt != "" {
		conn += fmt.Sprintf("    ; Possible values: %s, FAST-%s", connect, fastTxt)
		hm += fmt.Sprintf("          ; Possible values: HM0, HM2-%s", fastTxt)
	}
	return conn + "\n", hm + "\n"
}

func writeID(b *strings.Builder, key, val string) {
	fmt.Fprintf(b, "%-18s= {%s}\n", key, val)
}

func formatMeas(it record.Item) string {
	comment := it.Comment
	if it.Guessed && !strings.Contains(comment, "(guessed address)") {
		if comment != "" {
			comment += " "
		}
		comment += "(guessed address)"
	}
	s, inv := 0, 0
	if it.Signed {
		s = 1
	}
	if it.Inverse {
		inv = 1
	}
	return fmt.Sprintf("%-16s, {%-32s}, 0x%06X, %2d,  0x%04X, {%-8s}, %d, %d, %12s, %6s, {%s}",
		it.Name, it.Alias, it.Addr, it.Size, it.Bitmask, it.Unit, s, inv,
		formatNum(it.A), formatNum(it.B), comment)
}

func formatNum(v float64) string {
	return trimEq(record.FormatEq(v, 0, false))
}

func trimEq(eq string) string {
	eq = strings.TrimSuffix(eq, " * X")
	return eq
}

// MergeMy overlays my_<ecu> from the same directory onto f, by variable name.
func MergeMy(ecuPath string, f *File) error {
	dir, base := filepath.Split(ecuPath)
	my := filepath.Join(dir, "my_"+base)
	if _, err := os.Stat(my); err != nil {
		return nil
	}
	extra, err := Parse(my)
	if err != nil {
		return err
	}
	idx := map[string]int{}
	for i, it := range f.Items {
		idx[it.Name] = i
	}
	for _, it := range extra.Items {
		if i, ok := idx[it.Name]; ok {
			f.Items[i] = it
			continue
		}
		idx[it.Name] = len(f.Items)
		f.Items = append(f.Items, it)
	}
	return nil
}

func splitComma(s string) []string {
	var out []string
	var b strings.Builder
	depth := 0
	for _, r := range s {
		switch r {
		case '{':
			depth++
			b.WriteRune(r)
		case '}':
			if depth > 0 {
				depth--
			}
			b.WriteRune(r)
		case ',':
			if depth == 0 {
				out = append(out, strings.TrimSpace(b.String()))
				b.Reset()
				continue
			}
			b.WriteRune(r)
		default:
			b.WriteRune(r)
		}
	}
	out = append(out, strings.TrimSpace(b.String()))
	return out
}

func unwrap(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 && s[0] == '{' && s[len(s)-1] == '}' {
		return strings.TrimSpace(s[1 : len(s)-1])
	}
	return s
}

func latin1(b []byte) string {
	r := make([]rune, len(b))
	for i, c := range b {
		r[i] = rune(c)
	}
	return string(r)
}

func latin1Bytes(s string) []byte {
	b := make([]byte, 0, len(s))
	for _, r := range s {
		if r > 255 {
			b = append(b, '?')
			continue
		}
		b = append(b, byte(r))
	}
	return b
}
